version: '3.8'

services:
  lanproxy-client:
    build: .
    image: lanproxy-client:latest
    container_name: lanproxy-client
    restart: unless-stopped
    # 环境变量方式配置（可选）
    environment:
      - CLIENT_KEY=${CLIENT_KEY:-1716eb229b6f4d4f8ea755ec3cb7416f}
      - SERVER_HOST=${SERVER_HOST:-218.31.113.195}
      - SERVER_PORT=${SERVER_PORT:-9493}
      - ENABLE_SSL=${ENABLE_SSL:-true}
      - CERT_PATH=${CERT_PATH:-}
    # 命令行参数方式配置（推荐）
    command: [
      "-k", "${CLIENT_KEY:-1716eb229b6f4d4f8ea755ec3cb7416f}",
      "-s", "${SERVER_HOST:-218.31.113.195}", 
      "-p", "${SERVER_PORT:-9493}",
      "--ssl", "${ENABLE_SSL:-true}"
    ]
    # 如果需要使用SSL证书文件，取消注释以下行
    # volumes:
    #   - ./certs:/app/certs:ro
    # 网络模式（如果需要访问宿主机服务）
    # network_mode: "host"
    
    # 健康检查（可选）
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "lanproxy-client"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s